# 服务配置，配置IP、端口等
[server]
host = '0.0.0.0'            # 如需要任意IP访问，则填写:“0.0.0.0” 或 “::”
port = 21080
context = '/teamide'        # 如直接通过IP+端口访问，则填写:“” 或 “/”
data = './data'

# MySql配置
[mysql]
host = 'mysql'
port = 3306
database = 'teamide'
username = 'root'
password = '123456'

# Redis配置
[redis]
address = 'redis:6379'
auth = ''
# Key前缀，Team IDE所有存储将以该字符作为前缀
prefix = 'teamide'

# Zookeeper配置
[zookeeper]
address = 'zookeeper:2181'
# 根路径，Team IDE所有节点放在该节点下
namespace = '/teamide'

# Kafka配置
[kafka]
address = 'kafka:9092'
# Topic前缀，Team IDE所有Topic将使用该字符作为前缀
prefix = 'teamide'

# 日志配置
[log]
filename = "./log/server.log"
maxSize = 100                      # 文件大小单位M
maxAge = 7                         # 保留多少天
maxBackups = 10                    # 最多几个文件
level = "debug"                    # 级别，debug，info，warn，error