db:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: TEST_DB

db_2:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: TEST_DB

mongodb:
  address: 127.0.0.1:2181
  database: test_db
  minSize: 300
  maxSize: 300
  maxConnecting: 300
  maxWaitTime: 2000
  maxConnectionIdleTime: 15
  maxConnectionLifeTime: 2
  connectTimeout: 2000
  readTimeout: 3000

redis:
  type: standalone
  address: 127.0.0.1:6379
  password:

zk:
  address: 127.0.0.1:2181

kafka:
  address: 127.0.0.1:6379

es:
  url: 127.0.0.1:6379
