host: 0.0.0.0
port: 20120
contextPath: /demo.api
token:
  include: /**
  exclude: /token/create,/file/download/**,/file/open/**

  variables:
    - access_token:
        value: access_token
        dataPlace: header
  createService: token/create
  validateService: token/validate
  variableName: accessInfo
  variableDataType: accessInfo
